samples/features/security/ledger/source/ContosoHR/Models/LedgerVerification.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ContosoHR.Models
{
    public class LedgerVerification
    {
        public DateTime TimeStamp { get; set; }
        public string DigestLocations { get; set; }
        public string Result { get; set; }
    }
}

samples/features/security/ledger/source/ContosoHR/Pages/LedgerVerifications/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ContosoHR.Models;

namespace ContosoHR.Pages.LedgerVerifications
{
    public class IndexModel : PageModel
    {
        private readonly ContosoHR.Models.ContosoHRContext _context;

        public IndexModel(ContosoHR.Models.ContosoHRContext context)
        {
            _context = context;
        }

        public IList<LedgerVerification> LedgerVerifications { get; set; }

        public async Task OnGetAsync(string sortOrder)
        {
            LedgerVerifications = await _context.LedgerVerifications.FromSqlRaw("EXECUTE [dbo].[GetLedgerVerifications]").ToArrayAsync();
            /*
            IQueryable<LedgerVerification> ledgerVerificationIQ = from v in _context.LedgerVerifications
                                                                  orderby v.TimeStamp descending
                                                                  select v;

            LedgerVerifications = await ledgerVerificationIQ.AsNoTracking().ToListAsync();
            */
        }

        public async Task<IActionResult> OnPostVerifyAsync()
        {
            System.FormattableString query = $"EXECUTE [dbo].[VerifyLedger]";
            await _context.Database.ExecuteSqlInterpolatedAsync(query);
            return RedirectToPage("/LedgerVerifications/Index");
        }
    }
}

samples/features/security/ledger/source/ContosoHR/Pages/LedgerVerifications/Index.cshtml
@page
@model ContosoHR.Pages.LedgerVerifications.IndexModel

<h1>Ledger Verifications</h1>

<div class="row">
    <div class="col-lg-1">
        <form asp-page-handler="verify" method="post">
            <button class="btn btn-success" >Verify</button>
        </form>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>    
                @Html.DisplayNameFor(model => model.LedgerVerifications[0].TimeStamp)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LedgerVerifications[0].Result)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.LedgerVerifications) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TimeStamp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Result)
            </td>
        </tr>
}
    </tbody>
</table>